# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
title: ''
baseURL: 'https://yudabitrends.github.io/'

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: true
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## PAGE OPTIONS
############################

cascade:
  - target:
      path: /slides/**
      kind: page
    outputs: [HTML, present]

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
  hint: picture
timeout: 600000
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  _merge: deep
  highlight:
    lineNos: false
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
            - - \[
              - \]
            - - $$
              - $$
          inline:
            - - \(
              - \)
            - - $
              - $
        enable: true
security:
  _merge: deep
sitemap:
  _merge: deep
